config:
  project_repos:
    myrepo:
      repo: 'https://github.com/EOSC-synergy/FAIR_eva'
sqa_criteria:
  qc_style:
     repos:
       myrepo:
         container: fair_eva-testing
         tox:
           tox_file: /fair_eva-testing/tox.ini
           testenv:
            - pep8
